### ISSUE TITLE
SteelBlue1 is in there twice: 75 and 81

### ISSUE THREAD

**Issue by docwhat** [jonasjacek/colors#3]
The color SteelBlue1 is in there twice.  Once as 75 and once as 81

**Comment by docwhat** [comment]
In fact, scanning this it seems there are several duplicates:

- `Purple`: 5,93,129
- `Blue3`: 19,20
- `DeepSkyBlue4`: 23,24,25
- `DeepSkyBlue3`: 31,32
- `Green3`: 34,40
- `SpringGreen3`: 35,41
- `SpringGreen2`: 42,47
- `DarkRed`: 52,88
- `DeepPink4`: 53,89,125
- `Purple4`: 54,55
- `Orange4`: 58,94
- `SlateBlue3`: 61,62
- `DarkSeaGreen4`: 65,71
- `Chartreuse3`: 70,76
- `CadetBlue`: 72,73
- `SteelBlue1`: 75,81
- `PaleGreen3`: 77,114
- `Chartreuse2`: 82,112
- `SeaGreen1`: 84,85
- `Aquamarine1`: 86,122
- `DarkMagenta`: 90,91
- `DarkViolet`: 92,128
- `MediumPurple3`: 97,98
- `Yellow4`: 100,106
- `DarkOliveGreen3`: 107,113,149
- `LightSkyBlue3`: 109,110
- `DarkSeaGreen3`: 115,150
- `LightGreen`: 119,120
- `PaleGreen1`: 121,156
- `Red3`: 124,160
- `Magenta3`: 127,163,164
- `DarkOrange3`: 130,166
- `IndianRed`: 131,167
- `HotPink3`: 132,168
- `MediumPurple2`: 135,140
- `LightSalmon3`: 137,173
- `Gold3`: 142,178
- `Yellow3`: 148,184
- `DarkSeaGreen2`: 151,157
- `DarkSeaGreen1`: 158,193
- `DeepPink3`: 161,162
- `Magenta2`: 165,200
- `MediumOrchid1`: 171,207
- `LightGoldenrod2`: 186,221,222
- `DarkOliveGreen1`: 191,192
- `DeepPink1`: 198,199
- `IndianRed1`: 203,204
- `HotPink`: 205,206

**Comment by jonasjacek** [comment]
Hi @docwhat,
first of all, thanks for reporting and taking the time to inspect the issue. I have looked into this, and saw that other sources have the same 'issue'. So, although I do not know why this is the case, it does not really seem to be wrong. We see the same issue in http://vim.wikia.com/wiki/Xterm256_color_names_for_console_Vim for example. 
This site for example, https://www.rapidtables.com/web/color/RGB_Color.html, lists only 155 color name codes for RGB. Maybe this is where the limitation in my 256 list originates from.

**Comment by docwhat** [comment]
It’s a bug if the string is in the list twice. Some one messed. 

The original colors came from X11: https://en.m.wikipedia.org/wiki/X11_color_names

I’m guessing someone manually did the translation and messed up.

**Comment by jonasjacek** [comment]
I have investigated further. There seem to be other problems as well. 
For now, I have put out an errata warning. I have to fix this asap.

**Comment by docwhat** [comment]
Assuming this script is accurate, you could use it to recalculate the colors from the Wikipedia article:

https://gist.github.com/MicahElliott/719710
